apiVersion: v1
kind: Service
metadata:
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
  generateName: dev-8666f54c6d-8nth7-
  labels:
    app: tragicdev
    pod-template-hash: 8666f54c6d
  name: dev-8666f54c6d-8nth7-55slr
  namespace: default
spec:
  clusterIP: 10.219.243.65
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 30510
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: tragicdev
    pod-template-hash: 8666f54c6d
  sessionAffinity: None
  type: LoadBalancer
